DROP TABLE IF EXISTS relationships CASCADE;
CREATE TABLE relationships (
  id SERIAL PRIMARY KEY NOT NULL,
  user_one INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  user_two INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  status SMALLINT NOT NULL
);
